# Generated by Django 3.0.7 on 2020-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPI', '0003_auto_20200628_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
    ]
